# Generated by Django 4.0.4 on 2022-04-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
